'''Erstellen Sie eine GitHub Action “model-training.yml”, die folgende Aufgaben ausführt:
-	Repository Checkout
-	Python Setup mit Version 3.9 (oder alternativ die Version, die Sie lokal nutzen)
-	Python Dependency Installation
-	Model Training
-	Speichern des Modells als GitHub Artifact
'''

name: Train and Save Model

on:
  push:
    branches:
      - main

jobs:
  train_and_save_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model
        run: notepads/train.py

      - name: Save Model Artifact
        uses: actions/upload-artifact@v2
        with:
          name: saved_objects.pkl
          path: data/models/saved_objects.pkl
          


